name: two-do
region: ams

services:
  - name: web
    source_dir: /
    github:
      repo: LiamF-1/two-do
      branch: main
      deploy_on_push: true

    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs

    build_command: |
      npm ci --production=false
      npx prisma generate
      npm run build
    run_command: npm start

    # DigitalOcean sets PORT (8080). Next.js will read it.
    http_port: 8080

    envs:
      - key: NODE_ENV
        value: production
      - key: APP_URL
        value: ${APP_DOMAIN}
      - key: NEXTAUTH_URL
        value: ${APP_DOMAIN}
      - key: NEXTAUTH_SECRET
        value: ${NEXTAUTH_SECRET}
        type: SECRET
      - key: DATABASE_URL
        value: ${DATABASE_URL}
        type: SECRET
      - key: BCRYPT_ROUNDS
        value: "12"

    health_check:
      http_path: /api/health

    # Run DB migrations before swapping in the new release
    pre_deploy:
      - job: db-migrate

# Using existing DigitalOcean managed database
# databases:
#   - name: twodo-db
#     engine: PG
#     version: "15"
#     size: db-s-dev-database
#     num_nodes: 1

static_sites: []

jobs:
  - name: db-migrate
    kind: PRE_DEPLOY
    source_dir: /
    github:
      repo: LiamF-1/two-do
      branch: main

    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs

    # Apply pending migrations to the production DB before deploy
    run_command: |
      npx prisma migrate deploy

    envs:
      - key: DATABASE_URL
        value: ${DATABASE_URL}
        type: SECRET
