name: two-do
region: nyc

services:
  - name: web
    source_dir: /
    github:
      repo: LiamF-1/two-do
      branch: main
      deploy_on_push: true
    
    run_command: npm start
    build_command: |
      npm ci --production=false
      npx prisma generate
      npm run build
    
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    
    http_port: 3000
    
         envs:
       - key: NODE_ENV
         value: production
       - key: APP_URL
         value: ${APP_DOMAIN}
       - key: NEXTAUTH_URL
         value: ${APP_DOMAIN}
       - key: NEXTAUTH_SECRET
         value: ${NEXTAUTH_SECRET}
         type: SECRET
       - key: DATABASE_URL
         value: ${DATABASE_URL}
         type: SECRET
       - key: BCRYPT_ROUNDS
         value: "12"
    
    health_check:
      http_path: /api/health

# Using existing DigitalOcean managed database
# databases:
#   - name: twodo-db
#     engine: PG
#     version: "15"
#     size: db-s-dev-database
#     num_nodes: 1

static_sites: []

jobs:
  - name: db-migrate
    source_dir: /
    github:
      repo: LiamF-1/two-do
      branch: main
    
    run_command: |
      npx prisma db push --accept-data-loss
    
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    
    envs:
      - key: DATABASE_URL
        value: ${DATABASE_URL}
        type: SECRET
    
    kind: PRE_DEPLOY
